### ISSUE TITLE
(BuildContext, int) => dynamic' is not a subtype of type '(BuildContext, int) => Widget'

### ISSUE THREAD

**Issue by nitishk72** [FlutterRocks/movie-details-ui#3]
## Screenshot
![screenshot_1527940558](https://user-images.githubusercontent.com/15886737/40874215-34160df0-668a-11e8-926e-a235977f13da.png)

## Console Log
```
I/flutter (17893): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17893): The following assertion was thrown building PhotoScroller(dirty):
I/flutter (17893): type '(BuildContext, int) => dynamic' is not a subtype of type '(BuildContext, int) => Widget'
I/flutter (17893): 
I/flutter (17893): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17893): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17893): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17893):   https://github.com/flutter/flutter/issues/new
I/flutter (17893): 
I/flutter (17893): When the exception was thrown, this was the stack:
I/flutter (17893): #0      PhotoScroller.build (package:movie_details_ui/photo_scroller.dart:45:26)
I/flutter (17893): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
I/flutter (17893): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (17893): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #4      StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #6      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter (17893): #7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (17893): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #53     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #61     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #63     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter (17893): #64     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (17893): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #82     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #96     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #100    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #104    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #108    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #114    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #126    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #130    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #134    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
Reloaded 3 of 399 libraries in 940ms.
I/flutter (17893): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #140    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #146    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (17893): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #149    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #150    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (17893): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #152    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (17893): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #156    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (17893): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (17893): #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (17893): #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (17893): #160    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (17893): #161    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (17893): #162    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (17893): #163    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17893): #164    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17893): #165    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (17893): #167    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (17893): #168    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (17893): #169    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (17893): (elided one frame from package dart:async)
I/flutter (17893): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17893): Another exception was thrown: type '(BuildContext, int) => dynamic' is not a subtype of type '(BuildContext, int) => Widget'
```

**Comment by rayliverified** [comment]
This looks familiar :laughing: #1

**Comment by roughike** [comment]
Fixed.
